spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/termproject
    username: root
    password: neveralone

#  datasource:
#    driver-class-name: ${DRIVER_CLASS_NAME}
#    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  header: Authorization
  token-validity-in-seconds: 86400 # ${JWT_VALIDITY} # 86400